trigger:
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'

jobs:
  - job: Linux
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
      - script: |
          curl -sSf https://sh.rustup.rs | sh -s -- --default-toolchain stable -y
          echo "##vso[task.setvariable variable=PATH;]$(PATH):$(HOME)/.cargo/bin"
        displayName: 'Install rustup'

      - script: |
          cargo install cargo2junit
          rustup target add x86_64-unknown-linux-musl
          sudo apt-get -qq install musl-tools
        displayName: 'Add musl target'

      - script: cargo test -- -Z unstable-options --format json | cargo2junit > result.xml
        displayName: 'Tests'

      - script: cargo build --target=x86_64-unknown-linux-musl --release
        displayName: 'Build'

# vim:set ts=2 sts=2 sw=2:
