trigger:
 branches:
   include:
     - '*'

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    curl -sSf https://sh.rustup.rs | sh -s -- --default-toolchain $RUST_TOOLCHAIN -y
    echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
  displayName: 'Install rustup'

- script: |
    rustup target add x86_64-unknown-linux-musl
    sudo apt-get install musl
  displayName: 'Add musl target'

- script: cargo build --target=x86_64-unknown-linux-musl --release
  displayName: 'Build'
