trigger:
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'

jobs:
  - job: Linux
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
      - script: |
          curl -sSf https://sh.rustup.rs | sh -s -- --default-toolchain stable -y
          echo "##vso[task.setvariable variable=PATH;]$(PATH):$(HOME)/.cargo/bin"
        displayName: 'Install rustup'

      - script: |
          cargo install cargo2junit
          rustup target add x86_64-unknown-linux-musl
          sudo apt-get -qq install musl-tools
        displayName: 'Add musl target'

      - script: cargo test -- -Z unstable-options --format json | cargo2junit > results.xml
        displayName: 'Tests'

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: 'results.xml'
        condition: succeededOrFailed()

      - script: |
          cargo build --target=x86_64-unknown-linux-musl --release
          cp target/x86_64-unknown-linux-musl/release/pwl
        displayName: 'Build'

      - task: PublishBuildArtifacts@1
        inputs:
          artifactName: 'Linux'
          pathtoPublish: $(Build.ArtifactStagingDirectory)

  - job: Release
    dependsOn:
      Linux

    steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          downloadType: 'specific'
          itemPattern: '**'
          downloadPath: $(Build.ArtifactStagingDirectory)

      - script: ls $(Build.ArtifactStagingDirectory)

      - task: GitHubRelease@0
        inputs:
          gitHubConnection: 'yskszk63'
          repositoryName: 'yskszk63/pwl'
          tagSource: 'auto'
          assets: '$(Build.ArtifactStagingDirectory)/*/*'
          assetUploadMode: 'replace'
          isDraft: false
          isPreRelease: false
          addChangeLog: false
        displayName: Release to GitHub

# vim:set ts=2 sts=2 sw=2:
