[package]
name = "pwl"
version = "0.1.0"
authors = ["ysk"]
edition = "2018"

[dependencies]
clap = "2"
dirs = "1"
nix = "0.13"
#git2 = "0.8"

[dependencies.git2]
version = "0.8"
default-features = false
